### ISSUE TITLE
audit V5 contracts

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-protocol-eth#128]
branch identity-tests

- top priority: StakingPool, StakingMigrator
- second priority: OUTPACE, Guardian, SupplyController

Please write down your findings in a .md file report

**Comment by shteryana** [comment]
Мanual pre-deploy review was conducted (final at commit https://github.com/AdExNetwork/adex-protocol-eth/commit/c72185b981a19555716598740934b73b367286a5 , with units tests at https://github.com/AdExNetwork/adex-protocol-eth/commit/b8102d41ed5507b4ccc95c68fffd2f8dbfbad972) without any major issues reported. Automated security scanning/testing was performed using mythril & mythx which around the contract deployment time were the only Smart contract security tools supporting solc version 0.8.0+ . Several low severity issues were discovered mostly falling in the category "Solidity Coding Best Practices" which had been addressed/fixed. An attempt was made to downgrade the contracts to solc 0.6.12 and run a 'securfy' analysis, however results /report contained too many false positives because of the breaking changes in solc 0.8.0. (e.g. checking of all arithmetic by default). Post-deploy security scan was done running mythril at the addresses of the deployed contracts on mainnet without any major issues reported (the reported several low severity issues relating to the use of block.timestamp and  multiple calls to own codebase executed in the same transaction are intended by design).
